//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p8_prefija.CalculaPrefijaReferencia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculaPrefijaReferencia.CalculaPrefijaSoap")]
    public interface CalculaPrefijaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        p8_prefija.CalculaPrefijaReferencia.HelloWorldResponse HelloWorld(p8_prefija.CalculaPrefijaReferencia.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<p8_prefija.CalculaPrefijaReferencia.HelloWorldResponse> HelloWorldAsync(p8_prefija.CalculaPrefijaReferencia.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento expresion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Evaluar", ReplyAction="*")]
        p8_prefija.CalculaPrefijaReferencia.EvaluarResponse Evaluar(p8_prefija.CalculaPrefijaReferencia.EvaluarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Evaluar", ReplyAction="*")]
        System.Threading.Tasks.Task<p8_prefija.CalculaPrefijaReferencia.EvaluarResponse> EvaluarAsync(p8_prefija.CalculaPrefijaReferencia.EvaluarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public p8_prefija.CalculaPrefijaReferencia.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(p8_prefija.CalculaPrefijaReferencia.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public p8_prefija.CalculaPrefijaReferencia.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(p8_prefija.CalculaPrefijaReferencia.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvaluarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Evaluar", Namespace="http://tempuri.org/", Order=0)]
        public p8_prefija.CalculaPrefijaReferencia.EvaluarRequestBody Body;
        
        public EvaluarRequest() {
        }
        
        public EvaluarRequest(p8_prefija.CalculaPrefijaReferencia.EvaluarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expresion;
        
        public EvaluarRequestBody() {
        }
        
        public EvaluarRequestBody(string expresion) {
            this.expresion = expresion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvaluarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EvaluarResponse", Namespace="http://tempuri.org/", Order=0)]
        public p8_prefija.CalculaPrefijaReferencia.EvaluarResponseBody Body;
        
        public EvaluarResponse() {
        }
        
        public EvaluarResponse(p8_prefija.CalculaPrefijaReferencia.EvaluarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double EvaluarResult;
        
        public EvaluarResponseBody() {
        }
        
        public EvaluarResponseBody(double EvaluarResult) {
            this.EvaluarResult = EvaluarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculaPrefijaSoapChannel : p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculaPrefijaSoapClient : System.ServiceModel.ClientBase<p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap>, p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap {
        
        public CalculaPrefijaSoapClient() {
        }
        
        public CalculaPrefijaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculaPrefijaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculaPrefijaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculaPrefijaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        p8_prefija.CalculaPrefijaReferencia.HelloWorldResponse p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap.HelloWorld(p8_prefija.CalculaPrefijaReferencia.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            p8_prefija.CalculaPrefijaReferencia.HelloWorldRequest inValue = new p8_prefija.CalculaPrefijaReferencia.HelloWorldRequest();
            inValue.Body = new p8_prefija.CalculaPrefijaReferencia.HelloWorldRequestBody();
            p8_prefija.CalculaPrefijaReferencia.HelloWorldResponse retVal = ((p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<p8_prefija.CalculaPrefijaReferencia.HelloWorldResponse> p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap.HelloWorldAsync(p8_prefija.CalculaPrefijaReferencia.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<p8_prefija.CalculaPrefijaReferencia.HelloWorldResponse> HelloWorldAsync() {
            p8_prefija.CalculaPrefijaReferencia.HelloWorldRequest inValue = new p8_prefija.CalculaPrefijaReferencia.HelloWorldRequest();
            inValue.Body = new p8_prefija.CalculaPrefijaReferencia.HelloWorldRequestBody();
            return ((p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        p8_prefija.CalculaPrefijaReferencia.EvaluarResponse p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap.Evaluar(p8_prefija.CalculaPrefijaReferencia.EvaluarRequest request) {
            return base.Channel.Evaluar(request);
        }
        
        public double Evaluar(string expresion) {
            p8_prefija.CalculaPrefijaReferencia.EvaluarRequest inValue = new p8_prefija.CalculaPrefijaReferencia.EvaluarRequest();
            inValue.Body = new p8_prefija.CalculaPrefijaReferencia.EvaluarRequestBody();
            inValue.Body.expresion = expresion;
            p8_prefija.CalculaPrefijaReferencia.EvaluarResponse retVal = ((p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap)(this)).Evaluar(inValue);
            return retVal.Body.EvaluarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<p8_prefija.CalculaPrefijaReferencia.EvaluarResponse> p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap.EvaluarAsync(p8_prefija.CalculaPrefijaReferencia.EvaluarRequest request) {
            return base.Channel.EvaluarAsync(request);
        }
        
        public System.Threading.Tasks.Task<p8_prefija.CalculaPrefijaReferencia.EvaluarResponse> EvaluarAsync(string expresion) {
            p8_prefija.CalculaPrefijaReferencia.EvaluarRequest inValue = new p8_prefija.CalculaPrefijaReferencia.EvaluarRequest();
            inValue.Body = new p8_prefija.CalculaPrefijaReferencia.EvaluarRequestBody();
            inValue.Body.expresion = expresion;
            return ((p8_prefija.CalculaPrefijaReferencia.CalculaPrefijaSoap)(this)).EvaluarAsync(inValue);
        }
    }
}
